# Generated by Django 4.0.6 on 2022-08-24 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('gh_url', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_url', models.CharField(max_length=100)),
                ('num_methods', models.IntegerField(blank=True, null=True, verbose_name='number of methods')),
                ('num_classes', models.IntegerField(blank=True, null=True, verbose_name='number of classes')),
                ('num_method_examples', models.IntegerField(blank=True, null=True, verbose_name='number of methods with documentation examples')),
                ('num_class_examples', models.IntegerField(blank=True, null=True, verbose_name='number of classes with documentation examples')),
                ('last_updated', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=32)),
                ('library_name', models.CharField(max_length=50)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of software development experience')),
                ('used_before', models.BooleanField(blank=True, null=True, verbose_name='used before')),
                ('general_rating', models.CharField(blank=True, max_length=500, null=True)),
                ('task_list', models.CharField(blank=True, max_length=500, null=True)),
                ('code_examples_methods', models.CharField(blank=True, max_length=500, null=True)),
                ('code_examples_classes', models.CharField(blank=True, max_length=500, null=True)),
                ('text_readability', models.CharField(blank=True, max_length=500, null=True)),
                ('code_readability', models.CharField(blank=True, max_length=500, null=True)),
                ('consistency', models.CharField(blank=True, max_length=500, null=True)),
                ('navigability', models.CharField(blank=True, max_length=500, null=True)),
                ('usefulness', models.CharField(blank=True, max_length=500, null=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True, verbose_name='would recommend')),
                ('general_feedback', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=50)),
                ('paragraph', models.CharField(max_length=5000)),
                ('task', models.CharField(max_length=100)),
                ('has_example', models.BooleanField(verbose_name='has example')),
                ('example_page', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('session_key', 'library_name'), name='unique_session_library_combination'),
        ),
    ]
