# Generated by Django 4.0.3 on 2022-03-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=50)),
                ('num_methods', models.IntegerField(verbose_name='number of methods')),
                ('num_classes', models.IntegerField(verbose_name='number of classes')),
                ('num_method_examples', models.IntegerField(verbose_name='number of methods with documentation examples')),
                ('num_class_examples', models.IntegerField(verbose_name='number of classes with documentation examples')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=50)),
                ('paragraph', models.CharField(max_length=500)),
                ('task', models.CharField(max_length=100)),
                ('has_example', models.BooleanField(verbose_name='has example')),
            ],
        ),
    ]
