# Generated by Django 4.0.3 on 2022-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='paragraph',
            field=models.CharField(max_length=5000),
        ),
    ]
