# Generated by Django 4.0.6 on 2022-07-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('session_key', 'library_name'), name='unique_session_library_combination'),
        ),
    ]
